[profile.default]
libs = ["lib"]
names = true
sizes = true
via_ir = true
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "paris"

[profile.default.invariant]
runs = 16
depth = 256
fail_on_revert = true